node run_test.js tests/core/beget.js
node run_test.js tests/core/clone.js
node run_test.js tests/core/compare.js
node run_test.js tests/core/console.js
node run_test.js tests/core/guidFor.js
node run_test.js tests/core/inspect.js
node run_test.js tests/core/isArray.js
node run_test.js tests/core/IsEqual.js
node run_test.js tests/core/itemType.js
node run_test.js tests/core/keys.js
node run_test.js tests/core/makeArray.js
node run_test.js tests/core/objectForPropertyPath.js
node run_test.js tests/core/tupleForPropertyPath.js
node run_test.js tests/base/console.js
node run_test.js tests/mixins/array.js
node run_test.js tests/mixins/comparable.js
node run_test.js tests/mixins/enumerable.js
node run_test.js tests/mixins/propertyChanges.js
node run_test.js tests/system/binding.js
node run_test.js tests/system/cookie.js
node run_test.js tests/system/error.js
node run_test.js tests/system/logger.js
node run_test.js tests/system/run_loop.js
node run_test.js tests/system/set.js
node run_test.js tests/system/sparse_array.js
node run_test.js tests/private/observer_queue/isObservingSuspended.js
node run_test.js tests/mixins/observable/observable.js
node run_test.js tests/mixins/observable/propertyChanges.js
node run_test.js tests/mixins/observable/registerDependentKeys.js
node run_test.js tests/system/index_set/add.js
node run_test.js tests/system/index_set/addEach.js
node run_test.js tests/system/index_set/clone.js
node run_test.js tests/system/index_set/contains.js
node run_test.js tests/system/index_set/create.js
node run_test.js tests/system/index_set/indexAfter.js
node run_test.js tests/system/index_set/indexBefore.js
node run_test.js tests/system/index_set/intersects.js
node run_test.js tests/system/index_set/max.js
node run_test.js tests/system/index_set/min.js
node run_test.js tests/system/index_set/rangeStartForIndex.js
node run_test.js tests/system/index_set/remove.js
node run_test.js tests/system/index_set/removeEach.js
node run_test.js tests/system/index_set/without.js
node run_test.js tests/system/object/base.js
node run_test.js tests/system/object/bindings.js
node run_test.js tests/system/range_observer/create.js
node run_test.js tests/system/range_observer/destroy.js
node run_test.js tests/system/range_observer/objectPropertyDidChange.js
node run_test.js tests/system/range_observer/rangeDidChange.js
node run_test.js tests/system/range_observer/update.js
node run_test.js tests/system/selection_set/add.js
node run_test.js tests/system/selection_set/copy.js
node run_test.js tests/system/selection_set/indexSetForSource.js
node run_test.js tests/system/selection_set/isEqual.js
node run_test.js tests/system/selection_set/remove.js
